comments.c: Fix print_comment reading past the end of the buffer when reading less than a full comment from stdin.

diff --git a/regression/TEST b/regression/TEST
--- a/regression/TEST
+++ b/regression/TEST
@@ -424,6 +424,14 @@ echo Testing new comment stuff...Done.
 
 echo Testing bad code handling....
 
+# print_comment() was reading past the end of the buffer...
+echo -ne '/*' | $INDENT -npro -st > /dev/null 2>&1
+if [ $? -ne 0 ]
+then
+    echo "ERROR: print_comment reads past the end of the buffer." | tee -a $ERR
+    echo >> $ERR
+fi
+
 # This ends in a error from indent but it shouldn't coredump.
 $INDENT -npro input/bug206785.c -o output/bug206785.c 2>output/bug206785.err
 
